### ISSUE TITLE
[Bug] scale camera

### ISSUE THREAD

**Issue by PengWanYT** [ThDilos/Realistic-Fox-Origin#10]
**Versions**
**Minecraft Version: 1.21.1
**ModLoader & its Version: fabric / new latest
**Origins Mod Version: 1.13.0 alpha 9
**Fox Origin Version: 4.1.0

**Describe the bug**
Scale camera mess that where ride/seat

**To Reproduce**
When using fox origin to play, ride any minecar or animal & ride player, it make make camera not stay on player head, it's just make camera move to player button, but use normal origin, it's normal

**Expected behavior**
When same problem I am report that but using right Version mod, but the seat make camera kind mess, scale camera problem.

**Screenshots / Videos**
[Memory low]

**Comment by ThDilos** [comment]
This is actually an intended function. Your hitbox height is shrunk when you are riding a player / mob, because if not, you'll obstruct their visions. Your hitbox height is automatically resetted upon dismounting.

In the main recommended version (Minecraft 1.20.1, Origins 1.10.0), this power is performing as intended and your eye height won't be lowered down upon mounting.
However, in 1.21.1 versions, since something has been changed, either Pehkui or Minecraft base, your vision is somehow lowered again. (Also I found out that eye_height for Pehkui is not working at all it seems)

I will take note of this issue, and try to address in the next version.
Thanks for reporting.

**Comment by PengWanYT** [comment]
> This is actually an intended function. Your hitbox height is shrunk when you are riding a player / mob, because if not, you'll obstruct their visions. Your hitbox height is automatically resetted upon dismounting.
> 
> In the main recommended version (Minecraft 1.20.1, Origins 1.10.0), this power is performing as intended and your eye height won't be lowered down upon mounting. However, in 1.21.1 versions, since something has been changed, either Pehkui or Minecraft base, your vision is somehow lowered again. (Also I found out that eye_height for Pehkui is not working at all it seems)
> 
> I will take note of this issue, and try to address in the next version. Thanks for reporting.

Oh okkkk well np, cuz I am only one who found bug alot xD
